name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Buld on Ubuntu Latest arm64

    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2.2.0
        name: Run Commands
        id: build
        with:
          arch: aarch64
          distro: ubuntu_latest
          shell: /bin/bash
          install: apt-get update && apt-get install -y --no-install-recommends ca-certificates iputils-ping net-tools iproute2 openssh-client wget
          run: wget https://portal.domotz.com/download/agent_packages/domotz-debian-arm64-1.0-2.9.0-4.1.1-b001-0036.deb && dpkg -i domotz*
