name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./arm64 --file ./arm64/Dockerfile --tag domotz-agent-arm64:$(date +%s)
